version: 0.2

phases:
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - mvn clean package
      - ls -al
      - ls -al target
      - docker build -t kafka-connect-lambda:$CODEBUILD_BUILD_NUMBER .
      - docker tag kafka-connect-lambda:$CODEBUILD_BUILD_NUMBER 649894021925.dkr.ecr.us-east-1.amazonaws.com/onemata/kafka-connect-lambda:$CODEBUILD_BUILD_NUMBER
  post_build:
    commands:
      - docker push 649894021925.dkr.ecr.us-east-1.amazonaws.com/onemata/kafka-connect-lambda:$CODEBUILD_BUILD_NUMBER
artifacts:
  files:
    - 'target/plugin*/**'
  name: $CODEBUILD_BUILD_NUMBER
  discard-paths: yes
