version: 0.2

phases:
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-west-2)
  build:
    commands:
      - mvn clean package
      - docker build -t kafka-connect-lambda:latest .
      - docker tag kafka-connect-lambda:latest 649894021925.dkr.ecr.us-east-1.amazonaws.com/onemata/kafka-connect-lambda:latest
  post_build:
    commands:
      - docker push 649894021925.dkr.ecr.us-east-1.amazonaws.com/onemata/kafka-connect-lambda:latest  
artifacts:
  files:
    - 'target/plugin*/**'
  discard-paths: yes
