version: 0.2

env:
  variables:
    BUILD_NUM: build-$(Get-Date -UFormat "%Y%m%d-%H%M%S")
phases:
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - mvn clean package
      - ls -al
      - ls -al target
      - docker build -t kafka-connect-lambda:$Env:BUILD_NUM .
      - docker tag kafka-connect-lambda:$Env:BUILD_NUM 649894021925.dkr.ecr.us-east-1.amazonaws.com/onemata/kafka-connect-lambda:$Env:BUILD_NUM
  post_build:
    commands:
      - docker push 649894021925.dkr.ecr.us-east-1.amazonaws.com/onemata/kafka-connect-lambda:$Env:BUILD_NUM
artifacts:
  files:
    - 'target/plugin*/**'
  name: $Env:BUILD_NUM
  discard-paths: yes
